// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTZZceABo8fCy0OQKJC61XX86jAqzsKA',
    appId: '1:501213786425:web:4fc5a80cca0710c89078e8',
    messagingSenderId: '501213786425',
    projectId: 'travel-af56a',
    authDomain: 'travel-af56a.firebaseapp.com',
    storageBucket: 'travel-af56a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwl5gCoQX9xP2Tf4lI6rGRjJTfUF4oQ2A',
    appId: '1:501213786425:android:50c2a6ed0f1a0cce9078e8',
    messagingSenderId: '501213786425',
    projectId: 'travel-af56a',
    storageBucket: 'travel-af56a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IGU48W0FC14BqNGZsyQkMIjfNCC-0w8',
    appId: '1:501213786425:ios:d6bc295386a840119078e8',
    messagingSenderId: '501213786425',
    projectId: 'travel-af56a',
    storageBucket: 'travel-af56a.appspot.com',
    iosBundleId: 'com.example.travel',
  );
}
